config/routes.rb
LootApp::Application.routes.draw do
  get "products/view"
  get "products/new"
  get "password_resets/new"
  get "sessions/new"
  get "static_pages/home"
  get "static_pages/help"

  resources :sessions
  resources :password_resets
  resources :email_activations
  resources :bankaccts
  post "/bankaccts/new" => 'bankaccts#addbank'

  resources :products do
      resources :photos
      get :pics
  end
  resources :photos
  resources :requests do
    collection do
      get :activate
    end
  end
  resources :invitations do
    collection do
      get :accept_referral
    end
  end

  resources :users do
    collection do 
      get :accept_invitation
    end 
  end

  resources :transactions
  
  root to: 'static_pages#home'
  match "sign_up",      to: "users#new"
  match '/help',        to: 'static_pages#help'
  match '/log_in',      to: 'sessions#new'
  match '/log_out',     to: 'sessions#destroy'
  match '/remove_item', to: 'products#destroy'

end

app/models/user.rb
    class User < ActiveRecord::Base
      attr_accessible :email, :password, :password_confirmation, :name, :image, :photo
      
      attr_accessor :password
      before_save :encrypt_password
      before_save { |user| user.email = email.downcase }
      before_save { |user| user.name = name.downcase }
      before_create { generate_token(:auth_token) }
      before_create { generate_token(:email_token) }

      has_many :products, dependent: :destroy
      has_many :invitations
      has_many :photos,:through=>:products
      accepts_nested_attributes_for :products

      VALID_NAME_REGEX = /[a-zA-Z][a-zA-Z0-9]*/
      VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      VALID_PASSWORD_REGEX = /^(?=.*[a-zA-Z])(?=.*[0-9]).{6,}$/
      validates_confirmation_of :password
      validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
      validates :password, presence: true, format:{  with: VALID_PASSWORD_REGEX }, if: proc{ password_salt.blank? || password_hash.blank? } 
      validates :name, presence: true, format: { with: VALID_NAME_REGEX }, uniqueness: { case_sensitive: false }, length:  { minimum: 4 }

  def self.authenticate(email, password)
   user = find_by_email(email)
   if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
    user
   else  
    nil
  end
end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  def encrypt_password
  	if password.present?
  		self.password_salt = BCrypt::Engine.generate_salt
  		self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  	end
  end

def generate_token(column)
  begin
    self[column] = SecureRandom.urlsafe_base64
  end while User.exists?(column => self[column])
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :admin_and_user, only: [:destory, :edit, :show]
  before_filter :admin_user, only: :index
  before_filter :invited_user, only: :new

  def new
  	@user = User.new
    prepare_invitation
  end

  def create
    prepare_invitation
    params[:user][:email] = @invitation.email unless @invitation.nil?
    @user = User.new(params[:user])
  	if @user.save
      unless @invitation
        UserMailer.registration_confirmation(@user).deliver
      end
      if @invitation
        @user.email_activation_token = true
        @user.save
        cookies[:auth_token] = @user.auth_token
        redirect_to root_url, :notice => "Signed up."
      else
  		redirect_to root_url, :notice => "Signed up!"
      end
  	else
      if @invitation.present?
        render "new", :notice => "will not save but invitation present"
      else
        render "new"
      end
  	end
  end 

  def accept_invitation
      @user = User.find_by_email_token(params[:email_token])
      @user.email_activation_token = true
      @user.save!

      if Time.zone.now <= @user.created_at + 1.hour
        cookies[:auth_token] = @user.auth_token
        redirect_to root_url, :notice => "Email has been activated."
      else
        redirect_to root_url, :notice => "Email has been verified."
      end
  end

  def show
    @user = User.find(params[:id]) 
    @products = @user.products
  end

  def index
    @user = User.all
  end

  def update
    @user = User.find(params[:id]) 
    # binding.pry
    @user.password_hash = nil
    if @user.update_attributes(params[:user])
      redirect_to @user, :notice => "Password has been changed!"
    else
      render "edit"
    end
  end

 def edit
 end

 # def bankacct
 # end

 # def addbankacct
 #  if (params['customer_uri'])
 #    current_user.customer_uri = (params['customer_uri'])
 #  end
 #  if current_user.save
 #    redirect_to root_url, :notice => "bank account added"
 #  else
 #    render json: {error: "Payment account could not be configured properly"}, status: 401
 #  end 
 # end

 # def bankacct
 #  customer = Balanced::Customer.find(current_user.customer_uri) if current_user.customer_uri
 #  customer.add_bank_account(params['customer_uri'])
 #  if customer.save
 #    bank_account = Balanced::BankAccount.find(params['customer_uri'])
 #    render json: bank_account
 #  else
 #    render json: {error: "Payment account could not be configured properly"}, status: 401
 #  end 
 # end


  def destroy
  @user = User.find(params[:id]) 
  if @user.present?
    @user.destroy
    redirect_to root_url
  else
    redirect_to root_url, :notice => "Could not delete"
  end
  end

  def admin_and_user
    @user = User.find(params[:id]) 
    if current_user
      if current_user == @user || current_user.admin?
      else
        redirect_to(root_url)
      end
    else
      redirect_to(root_url)
    end
  end

private 
  def prepare_invitation 
    return unless params[:invite_token].present? 
    @invitation = Invitation.find_by_invite_token(params[:invite_token]) 
    redirect_to log_in_path, notice: "Already registered" if User.where(email: @invitation.email).exists? 
  end

  def invited_user
    redirect_to root_url if params[:invite_token].nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.haml
- provide(:title, 'lootfly | ' +  @user.name)
%h1
  Change password
%p
  = form_for @user do |f|
    - if @user.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
          - for message in @user.errors.full_messages
            %li
              = message
    .field
      = f.label :password
      = f.password_field :password
    .field
      = f.label :password_confirmation
      = f.password_field :password_confirmation
    .actions
      = f.submit "Update Password"

app/views/users/index.html.haml
%h1
  List of users (
  = @user.count
  )
%p
  - @user.each do |user|
    %p 
      = user.name
      %b Email
      = user.email
      %b User ID
      = user.id
      = link_to 'Show', user
      - unless user.admin?
        = link_to 'Delete', user, method: :delete, data: { confirm: "Are you sure?" }

app/views/users/new.html.haml
- provide(:title, 'lootfly | Create Account')
%h1 
  sign up

= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li
            = message
  %p
    = f.label :name
    = f.text_field :name

  - if @invitation
    = hidden_field_tag :invite_token, @invitation.invite_token

  - if @invitation.nil?
    %p
      = f.label :email
      = f.text_field :email
  %p
    = f.label :password
    = f.password_field :password
  %p
    = f.label :password_confirmation
    = f.password_field :password_confirmation

  %p.button
    = f.submit

app/views/users/newbankacct.html.haml
%p
  go

app/views/users/show.html.haml
- provide(:title, 'lootfly | ' +  @user.name)
%p

  %b Name
  = @user.name
  %br

  %b Email
  = @user.email
  %br

  %b Member since
  = @user.created_at
  %br
  - if @user.admin == false
    - if current_user.admin?
      = link_to 'Delete this users account', @user, method: :delete, data: { confirm: "Are you sure? This will delete your account" }
    - else
      = link_to 'Delete your account', @user, method: :delete, data: { confirm: "Are you sure? This will delete your account" }
  - else
  %br

  %h3
    - if @user.admin?
      Items this user is selling
    - else
      Items your selling



- @products.each do |product|
  %p
    = product.name
    %b
    = link_to 'Show', product
    = link_to 'Edit', edit_product_path(product)
    = link_to 'Delete', product, method: :delete, data: { confirm: "Are you sure?" }
%br
- unless @user.admin?
  = link_to 'Reset password', edit_user_path(@user)