config/routes.rb
LootApp::Application.routes.draw do
  get "products/view"
  get "products/new"
  get "password_resets/new"
  get "sessions/new"
  get "static_pages/home"
  get "static_pages/help"

  resources :sessions
  resources :password_resets
  resources :email_activations
  resources :bankaccts
  post "/bankaccts/new" => 'bankaccts#addbank'

  resources :products do
      resources :photos
      get :pics
  end
  resources :photos
  resources :requests do
    collection do
      get :activate
    end
  end
  resources :invitations do
    collection do
      get :accept_referral
    end
  end

  resources :users do
    collection do 
      get :accept_invitation
    end 
  end

  resources :transactions
  
  root to: 'static_pages#home'
  match "sign_up",      to: "users#new"
  match '/help',        to: 'static_pages#help'
  match '/log_in',      to: 'sessions#new'
  match '/log_out',     to: 'sessions#destroy'
  match '/remove_item', to: 'products#destroy'

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :activated, :email

  before_save { |request| request.email = email.downcase }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_filter :admin_user, only: :index

  def new
  	@request = Request.new
  end
  
  def index
    @requests = Request.all
  end

  def activate
    @request = Request.find(params[:request_id])
    @invitation = Invitation.new
    @invitation.email = @request.email
    @invitation.user_id = current_user.id
    @invitation.save!
    @request.activated = true
    @request.save!
    # redirect_to requests_path, :notice => "Invitation sent!"
    UserMailer.invitation(@invitation).deliver
  end

  def create
  	@request = Request.new(params[:request])
  	if @request.valid?
      if User.find_by_email(@request.email) || Invitation.find_by_email(@request.email)
      	redirect_to log_in_path, notice: "Email already in use"
      elsif @request.save
      	@request.save
        @temporary_request = @request
      	redirect_to root_url, :notice => "Request sent."
      	UserMailer.request_invitation(@temporary_request).deliver
      end
  	else
  		render "new"
  	end
  end
end

app/views/requests/activate.js.erb
$(document).ready(function(){
    $('.ajaxlink').on('click',function(){
        $(this).hide();
    });
});

app/views/requests/index.html.haml
%h1
  requests (
  = @requests.count
  )
%p
  - @requests.each do |x|
    %p 
      = x.email
      %b
        Created at:
      = x.created_at
      - if x.activated == false
        = link_to 'activate', activate_requests_path(:request_id => x.id), remote: true, :class => "ajaxlink"

app/views/requests/new.html.haml
%h1
  Request an invite

= form_for @request do |f|
  - if @request.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @request.errors.full_messages
          %li
            = message
  %p
    = f.label :email
    = f.text_field :email
  %p.button
    = f.submit