config/routes.rb
LootApp::Application.routes.draw do
  get "products/view"
  get "products/new"
  get "password_resets/new"
  get "sessions/new"
  get "static_pages/home"
  get "static_pages/help"

  resources :sessions
  resources :password_resets
  resources :email_activations
  resources :bankaccts
  post "/bankaccts/new" => 'bankaccts#addbank'

  resources :products do
      resources :photos
      get :pics
  end
  resources :photos
  resources :requests do
    collection do
      get :activate
    end
  end
  resources :invitations do
    collection do
      get :accept_referral
    end
  end

  resources :users do
    collection do 
      get :accept_invitation
    end 
  end

  resources :transactions
  
  root to: 'static_pages#home'
  match "sign_up",      to: "users#new"
  match '/help',        to: 'static_pages#help'
  match '/log_in',      to: 'sessions#new'
  match '/log_out',     to: 'sessions#destroy'
  match '/remove_item', to: 'products#destroy'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    = stylesheet_link_tag "application", :media => "all"

    %script{:src => "https://js.balancedpayments.com/v1/balanced.js", :type => "text/javascript"}
    :javascript
      balanced.init('${/v1/marketplaces/TEST-MP5JtbXVDZkSGruOJyNasPqy}');
      
    = javascript_include_tag "application"
    = javascript_include_tag "autoNumeric"



    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=Dosis:400,600", :rel => "stylesheet", :type => "text/css"}

  %body
    %nav
      .inner
        / = link_to image_tag("logo.png", alt: "Logo"), root_url
        #menu
          - if current_user 
            = link_to "Invite", new_invitation_path
            = link_to "Sell", products_new_path
            = link_to "My account", current_user
            - if current_user.admin?
              = link_to "Users", users_path
              = link_to "Products", products_path
              = link_to "Invitations", invitations_path
              = link_to "Requests", requests_path
            = link_to "log out", log_out_path
          - else
            = link_to "Request invite", new_request_path
            / = link_to "Sign up", sign_up_path
            / or
            = link_to "log in", log_in_path
  
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, :id => "flash_#{name}"
    = yield